services:
  hungree-api:
    build:
      context: ./api
      args:
        - api_port=3000
        - ui_port=3001
        - NODE_ENV=production
    container_name: hungree-api
    environment:
      - API_PORT=3000
      - UI_PORT=3001
      - NODE_ENV=production
    working_dir: /app
    ports:
      - 3000:3000
    command: node index.js
  hungree-ui:
    build:
      context: ./ui
      args:
        - api_port=3000
        - ui_port=3001
        - NODE_ENV=production
    ports:
      - 3001:3001
    container_name: hungree-ui
    environment:
      - API_PORT=3000
      - UI_PORT=3001
      - NODE_ENV=production
    working_dir: /app
    command: npm run dev -- --host --port 3001
    depends_on:
      - hungree-api
  hungree-cli:
    build:
      context: .
      args:
        - api_port=3000
        - ui_port=3001
        - node_env=production
    environment:
      - API_PORT=3000
      - UI_PORT=3001
      - NODE_ENV=production
    container_name: hungree-cli
    working_dir: /app
